server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.29.128:3306/mall-tiny?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
